spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cuffee_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: sa
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver